language: java
env:
  global:
  - secure: "e/uKgI0JTZjTkPbluHNIvB2rL/K+XsKwRtgwEOORxafiJwwkAeg97LPGs5+Ie+QXSQ0q25ApqT5XUCUsGJNZFZkXtyU6vpvsxWvFXcBAMWKmUmVW2+WmsCYJ7cdGgiRnPWHj+I16P5sOY7avPjxTPU3tt5+UnDwiKMRKrjvRX+yiAgsPE2yfmaVZnOfS8Pz4GYllW9bGlo+RPXBQt9/lgfFVney5YsK0rj0a8+w5EfAjDHxjedbq34q/KXRt4ehKAs3T3WS+0PyJ7JZSofnEJeJ1cuIJZpZlBjSPHYYC3Sx78sRC6qqHfpfThCEznazAwXouJcZ65WTEVr5bGtYXZH/32gBRODYEcncpISy7I7A6h7Xad7xXpU6VOp8GbbbWHt2k+WR8PeX9NL094Irn1YN58HaH8qkQ+TcSQ1h5ygndwe6HP1sz0tmA0lES81+l2mSqZGa+mFqf/1MQJV7AISI3dMrYf9Oa7arXOC2tDXgCnYEG6K2KWdMLLM9p/w7wk/9qELwbRHUKzdc90l1RYBe1NH46WA2HAsFeQl65YYF9B6RxeDPPyuOx+UhNrMKMU4xeRBdmQ3xh6BiULU0Jb/Q5fMkdMtyp+sJCZ40w1ep/fFwuuWtc+O8VzIwTm0MP4yKU9stYKtu2H81grrbX3cSYmiTSveDoPXLOvBQ0y40="
  - secure: "BqyZgs7VdN7S1vdKil0l3mi9NMq9WBxPEFI+j9beCHH2igPmZ2FaiQxo7d058pZhOnon9f1Xp2lBoXj3PD2UTJ3Q7wUVr4oyLDgRgE+QfJ0mzkt6wP+8LBRG+vFj+9rO/F196m230QDN4eKK8Y+EBU6oF4ip01++SGh8ILMnwZx5kd2/UvpudOKs93FgBNJZBVnp/NcNHJqs6j14VR+QpDNtF0shNNg71OPh94sXucgakTsRu/Ahmy7cJVLoire4f5PxW5niE7cvcwnSSW/pwxgOJ64FCZ92mlfZvkYj4OBjEloVOoNcB2/op0nSXHPHCnwQSoqt1x4YV+idL9bhptNRa01PD2w5QCGVQ4DJpT5bfSdXLOAPAD+FMqkKYs0IDVMMtvR0oAvUVeqNOHzCV9WkyZ7hiDxGTRVEFIv+RdJZNjZ10P9JdAZwaEZusFSYe4gPA0/Fh7ORT9jzb/WUWQFhQEsKK1Ke+vzoVn3fhpUwFReTFCLBTwTke5SIwHPrszC+oUi8M7h8/YAnp0hLIHpduW0B9gQ6NGc0eWvE3dJUm2ADPZCpylE37fRkrmlnuyasRFWH0Xqp2eyI3es6MZ/hsH0IJrEiodR3hDtjomYkqRbOqrzW58S54BQvY2gKb+a0xODgBBzAOvGubjrcZRg7yGfLviH/Zz93KYq2XQk="

addons:
  sonarcloud:
    organization: "brianereynolds-github"
    token:
      secure: "T9OxbUF/2aLgzJpSgYNpoxzZvyMMKNt7yFWJ1OQFk8UbRXPjefi5hM803dlZgp1X2XbE1umcPiuFNuF5PL5xOSwk9SsnIORm3/fCIL4+S7s4wxsAl+CGaVACxBEOnwkuYlZ662viuQ1mHqaOAOZ0GIwBjUMRCF6lWCQ28SqZLQpeXjCH/p9wLdeyuLjR6PMQBrIoiNX6w7CZFeFfGn3xpOMZItfme35/rbZrJ+dIpnuAyjV8B2coovaUDXqBBFjhVCkeSJO5Sv6G0ovNSh4V4RL9hr8TG+WxZuE/jsRvaZ5B8iIDwExBsiIyVJKnOhDz1cXV/8s+3ysJo74wtO1v2FU4lAT1+BHhWcwa2mdHjATFyAltsGZwzFsAw/W8PqWtFRkxBnjW8dE5q8IKg0uWA9GIljOSZaqKvyJhA8vcLpZkekeNqUazdZ11R6tUs/BDIapoAY3xN3qn/KFQla0crZK9n6I2AvYlI5gkjF4V5N0i3eGXcwDLeaEQS8tZ7yzFrP4Sba/QsuP/qy4FhQqhm21p8i8St+Xs701lzlxOn7/oMmbIRGfCQ3jIMu+kLgOIstgtQjInmt8fKzvulRj90ab0MR3HKc145Dszryf1oZK9f/MtmPTKMF2zS5jfzXrCAAy5lguluYLpIuH1/+BeRo64pMZyBHwIi7xgRlDnGz0="

script:
  - sonar-scanner

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export REPO=$DOCKER_USERNAME/atm-machine
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO .
  - docker tag `docker images -q $REPO` $REPO:$TAG
  - docker push $REPO
