server:
  port: 7000

spring:
  main:
    banner-mode: "off"
  datasource:
    url: "jdbc:h2:./database/atmdb;AUTO_SERVER=true"
    driverClassName: "org.h2.Driver"

logging:
  level:
    ROOT: ERROR
    org.springframework: INFO
    com.mybank: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"